server:
  # 指定该Eureka实例的端口
  port: 8761

eureka:
  instance:
    # 指定该Eureka实例的主机名
    hostname: localhost
    preferIpAddress: true
  server:
    # 关闭自我保护机制
    enableSelfPreservation: false
    #  清理无效的服务节点，清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 10000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode